### ISSUE TITLE
Search by Type times out on the system

### ISSUE THREAD

**Issue by cbarrieau232** [cbshashank/swegroup-4#8]
Searching by type times out on the C# system.  To test, just do a search by type with the front end.

**Comment by cbarrieau232** [comment]
Updated to remove duplicate ID checking to improve performance.

**Comment by cbarrieau232** [comment]
There are general timing issues which we might need to address as part of phase III

**Comment by cbarrieau232** [comment]
This appears to be if we search by "Shrub".  Might be my machine, needs further testing.

**Comment by cbarrieau232** [comment]
Updated code so that the search no longer times out.  However large queries of results take a long time to display.  Will create a separate issue.

**Comment by cbarrieau232** [comment]
Issue appears sporadically on my machine - may want to test on someone else's PC to see what happens.

**Comment by sag129** [comment]
Showing the Type="Shrub" query works in 40s.

Let's use ajax toggle (http://www.w3schools.com/jquery/eff_toggle.asp) to manage the performance time better with iframes for a few plants rather than all of them.  You can toggle for more information in an iframe once you find a plant of interest based on its picture.

**Comment by cbarrieau232** [comment]
Closing this issue - type appears to time out when the system is heavily using RAM, and this is also a duplicate with the issue on the Results window.
